export const HfMessages = {
    HF_MOD_LOAD_ERR: 'Unable to load Hugging Face models.',
    HF_IMA_TYPE_ERR: 'Only PNG and JPEG images are allowed.',
    HF_PROC_ERR: 'An error occurred while processing the request.',
    HF_MOD_ADD: 'Add Model.',
    HF_MOD_ADD_SUCC: 'The model was added successfully.',
    HF_ERR: 'Error.',
    HF_ADD_ERR: 'An error occurred while adding the model.',
    HF_MOD_NICK: 'Please enter a model nickname.',
    HF_MOD_NICK_RESTR: 'Model nickname must not exceed 15 characters.',
    HF_MOD_NAM: 'Please enter a model name.',
    HF_MOD_OPER: 'Please select an operation type.',
    HF_MOD_TYPE: 'Please enter the model type.',
    HF_MOD_DEL: 'Delete Model.',
    HF_MOD_DEL_FAIL: 'Failed to delete the model.',
    HF_MOD_DEL_ERR: 'An error occurred while deleting the model.',
    HF_MOD_TEMP: 'Please enter the temperature value.',
    HF_MOD_MAX_TOKEN: 'Please enter the maximum token value.',
    HF_MOD_UPDATE: 'Update Model.',
    HF_MOD_UPDATE_SUCC: 'The model was updated successfully.',
    HF_UPDATE_ERR: 'An error occurred while updating the model.',
    HF_IMAGE_UPLOAD_PATTERN: 'Only JPG and PNG files are allowed.',
    HF_IMAGE_MAX_SIZE: 'Image must be smaller than 2MB.',
    HF_FETCH_MODL_FAIL: 'Failed to fetch Hugging Face models.',
    HF_TOKEN_UPDATE_FAILED: 'Failed to update the token. Please try again.',
    HF_TOKEN_UPDATE_ERROR: 'An unexpected error occurred while updating the token.',
  };